### ISSUE TITLE
Show "No items yet" for concept and schema lists

### ISSUE THREAD

**Issue by cferdinandi** [polyneme/heliokos#10]
When a new user does not have any existing concepts or schemes, we should show a "You don't have any {concepts/schemas} yet, click here to create one" type messaging. This will require some if/else logic in the python templating that I'm not familiar with.

**Comment by dwinston** [comment]
I added a commit to a new branch, <https://github.com/polyneme/heliokos/tree/no-items-yet>, that includes relevant python templating, but then the interactive, no-page-reload case is broken, in that I get an updated status message, but no appearance of the item:

<img width="490" alt="image" src="https://github.com/polyneme/heliokos/assets/1497854/41a5adee-d17f-42fc-8ea1-cb6eb66f1f4a">

I trust you to go with whatever approach for this. perhaps sending the has-items template with the initial response, for the javascript to grab and populate? up to you.
