### ISSUE TITLE
Update how UI updates are rendered

### ISSUE THREAD

**Issue by cferdinandi** [polyneme/heliokos#16]
As the UI evolves, managing DOM updates is going to get a bit more challenging.

I've got a small refactor in mind that extends the work we've already done and makes use of the HTML the server responds with when making `POST` calls after form actions.

In short, I'll be refactoring how the updated sections of the UI are rendered after form submissions to make long-term maintenance a bit more manageable.

**Comment by cferdinandi** [comment]
**Details**

Create a custom web component for forms: `<hk-form>` that wraps around the default form elements.

```html
<hk-form>
	<form class="usa-form" method="post" action="/conceptscheme">
		<button class="usa-button">
			Create Concept Scheme
		</button>
	</form>
</hk-form>
```

By default, the form will work with full server loads, no JS needed.

When the web component JavaScript loads, it enhances the form behavior with JavaScript by making Ajax form submissions, and selectively updating the UI.

The desired behavior can be controlled with custom attributes on the `hk-form` element...

```html
<hk-form default="prevent" submitting="Creating a new concept" success="New concept created">
    <!-- ... -->
</hk-form>
```

No extra work needed on your end, @dwinston. This should be ready tomorrow. Just requires a little moving around of some existing code.

**Comment by cferdinandi** [comment]
Pending PR review...

**Comment by dwinston** [comment]
thanks! I hope to review this first thing tomorrow morning.

**Comment by cferdinandi** [comment]
@dwinston You'll notice it looks a lot like the HTMX you already had in (but adds some UI niceties and accessibilities fixes, and is a fraction of the size).

**Comment by dwinston** [comment]
yes, very nice with the declarative style using attributes in the web component.
