### ISSUE TITLE
The same concept can be added to a scheme multiple times

### ISSUE THREAD

**Issue by cferdinandi** [polyneme/heliokos#26]

**Comment by dwinston** [comment]
yes, please address this.

**Comment by cferdinandi** [comment]
@dwinston I'll add some JS logic to disable already added items. We should probably add some server logic to throw an error in those situations.

**Comment by dwinston** [comment]
> I'll add some JS logic to disable already added items.

great. please proceed. 

> We should probably add some server logic to throw an error in those situations.

agreed. won't close this issue until I have server-logic coverage.

**Comment by cferdinandi** [comment]
PR for client side fix. I also added some server-side logic to only render `<option>` elements for concepts that aren't already in the scheme. The client side fix re-updates the HTML after the form submits.

**Comment by cferdinandi** [comment]
🎉🎉🎉
