### ISSUE TITLE
Design/UI Recommendations

### ISSUE THREAD

**Issue by cferdinandi** [polyneme/heliokos#3]
After going through the app, I've got a few ideas for how to improve the UI. Video attached walking through it, but the high-level concepts are...

- Two new routes to view all _Concepts_ and all _Schemes_ (ideally the existing routes for those but without an ID in the path)
- On the new _All Concepts_ page, embed the form to create a new one
- On the new _All Schemes_ page, embed the form to create a new one
- When creating new concepts from the homepage, do _not_ immediately redirect to the new concept. List all concepts on the homepage like schemes are, and update the list dynamically. That way users can create a few concepts, them jump in and create a scheme, without getting tossed around the UI so much.

https://github.com/polyneme/heliokos/assets/1724852/e9969abc-4609-4d5b-b6c5-9ec8f4ae1b6c

**Comment by dwinston** [comment]
That all sounds great. Please move forward. I've tried to implement routes and stub templates for the Concept and ConceptScheme collection views, so that you don't need to dive into any Python. Let me know if you need anything else from me to complete this.

**Comment by cferdinandi** [comment]
Awesome! I'll probably split this into a few smaller subtasks, and get cranking on it soon!

**Comment by dwinston** [comment]
love love love the improved UI. thanks for your initiative on seeking a NASA design system.

**Comment by cferdinandi** [comment]
@dwinston Glad to hear it! How do you feel about the inclusion of the NASA logo? Is that appropriate here, or should it be something else?

**Comment by dwinston** [comment]
NASA logo seems fine as long as this is only deployed for internal review. Perhaps a slight improvement would be replacing that with (a scaled version of) the sun and earth picture at the top of https://hdrl.gsfc.nasa.gov/ ? Let's go with that if the result isn't (too) ugly.

**Comment by dwinston** [comment]
Ooh or maybe the [HelioCloud](http://heliocloud.org/) logo. The contact at the bottom of that page (B. Thomas) is involved in *this* project as well. I'll stop now. Logo not important for now. :) Go with whatever you feel is good. :)

**Comment by cferdinandi** [comment]
@dwinston For accessibility reasons, I'm also going to recommend we drop HTMX in favor of full page loads.

The stock implementation fails to shift focus correctly or notify screen reader users of UI changes. That's always an issue, but for government-related projects, it's particularly important to get right.

If you're OK with, I can update any existing code to provide the same user experience but without HTMX (or the accessibility issues).

**Comment by dwinston** [comment]
Go for it (i.e., close #4). Thank you.

**Comment by dwinston** [comment]
seems like the stated recommendations are done, so closing this. feel free to open a fresh issue with new design/ui recommendations if applicable.
