### ISSUE TITLE
hk-combo-box pattern needs to escape parentheses?

### ISSUE THREAD

**Issue by dwinston** [polyneme/heliokos#31]
Some of the values have parentheses in them. I found that the following took care of it. But perhaps you know of a more robust way?

```js
// Set [pattern] attribute for validation
		let pattern = data.map((item) => item.value.replace('(', '\\(').replace(')','\\)')).join('|');
```

**Comment by dwinston** [comment]
I want to make sure the pattern enumeration represents each data item literally, even if it has characters that have special meaning in a regex context.

**Comment by cferdinandi** [comment]
@dwinston That was definitely the intent, sorry! I forgot special characters might be a thing here. I'll look into this!

**Comment by cferdinandi** [comment]
@dwinston Just implemented a fix for this (pushed directly to `main`, sorry), that should escape all RegEx special characters. There's a browser-native `RegExp.escape()` method in the works, but it's not implemented everywhere yet, so for now, we use a helper function.

**Comment by dwinston** [comment]
just tested it on a concept with parentheses. worked well. thanks!
